# Generated by Django 3.2.9 on 2022-04-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
    ]
