# Generated by Django 3.2.9 on 2022-04-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='b',
        ),
    ]
