# Generated by Django 3.2.9 on 2022-04-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_remove_exp_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exp',
        ),
    ]
